name: Run ASCII Script


on:
  push:
    branches: [ main ]


jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: List Files Before Run
        run: ls -ltra


      - name: Make script executable then run it
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh
          

      - name: After all, check permission
        run: |
          echo "After chmod"
          ls -ltra