name: Run ASCII Script


on:
  push:
    branches: [ main ]


jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: List Files Before Run
        run: ls -ltra


      - name: Run Script
        run: ./ascii-script.sh